# Generated by Django 2.0.1 on 2018-01-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=455)),
                ('cover_art', models.CharField(max_length=455)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=455)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'track',
                'managed': False,
            },
        ),
    ]
